### PR TITLE
chore-issue-390: update dep of rerelease 2.0.0

### PR DESCRIPTION
**Pull request by fospring**

### CODE REVIEW

**Comment by ailisp** [comment]
Looks good! Let's also add:
- npm scripts to deploy the contract to testnet (create a dev account and deploy), deploy to mainnet and mention that in readme. 
- add a CI to ensure build, test and deploy to testnet works

**Comment by fospring** [comment]
> Looks good! Let's also add:
> 
> * npm scripts to deploy the contract to testnet (create a dev account and deploy), deploy to mainnet and mention that in readme.
> * add a CI to ensure build, test and deploy to testnet works

okay

**Comment by fospring** [comment]
> Looks good! Let's also add:
> 
> * npm scripts to deploy the contract to testnet (create a dev account and deploy), deploy to mainnet and mention that in readme.
> * add a CI to ensure build, test and deploy to testnet works

it seems that workspaces is not support `mainnet` network: [worker.js](https://github.com/near/near-workspaces-js/blob/main/packages/js/dist/worker.js#L50)

**Comment by fospring** [comment]
CI added in this MR: https://github.com/near/near-sdk-js-template-project/pull/17

**Pull request closed without merging**
